CREATE TABLE public.members (
    member_id integer NOT NULL,
    display_as text NULL,
    full_title text NULL,
    gender text NULL,
    party text NULL,
    house text NULL,
    constituency text NULL,
    house_start_date timestamp with time zone NULL,
    constituency_country text NULL,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    house_end_date timestamp with time zone NULL,
    twfy_url text NULL,
    twfy_image_url text NULL,
    email text NULL,
    age smallint NULL,
    peerage_type text NULL,
    department text NULL,
    ministerial_ranking smallint NULL,
    media jsonb NULL,
    badge_title text NULL,
    last_updated_at timestamp with time zone NULL DEFAULT now(),
    last_updated_by text NULL,
    twfy_id text NULL,
    CONSTRAINT members_pkey PRIMARY KEY (member_id)
);